name:                linear-tests
version:             0.1.1.0
github:              "pdlla/linear-tests"
license:             BSD3
author:              "pdlla"
maintainer:          "chippermonky@gmail.com"
copyright:           "2020 pdlla"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pdlla/linear-tests#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- linear
- lens

library:
  source-dirs: src
  exposed-modules:
    - Linear.Arbitrary
    - Linear.Matrix.Arbitrary
    - Linear.Quaternion.Arbitrary
    - Linear.V3.Arbitrary
    - Linear.V4.Arbitrary

tests:
  linear-tests-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linear-tests
    - hspec
    - hspec-core
