name:                linear-tests
version:             0.1.0.0
github:              "githubuser/linear-tests"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/linear-tests#readme>

ghc-options:
- -Wall

default-extensions:
- InstanceSigs
- LambdaCase
- OverloadedStrings
- GADTs
- FlexibleInstances
- FlexibleContexts
- ScopedTypeVariables
- MultiWayIf
- TupleSections
- MultiParamTypeClasses

dependencies:
- base >= 4.7 && < 5
- QuickCheck

library:
  source-dirs: src

tests:
  linear-tests-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - linear-tests
    - hspec
